server:
  port: 9090

spring:
  application:
    name: ApiGateWayApp
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PATCH
              - PUT
              - DELETE
eureka:
  client:
    fetch-registry=true
    register-with-eureka=true


